name: Build and deploy PHP app to Azure Web App - wwwpaybitcoininth

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-disk-space:
    runs-on: ubuntu-latest

    steps:
      - name: Check Disk Space
        run: df -h

  build:
    runs-on: ubuntu-latest
    needs: check-disk-space

    steps:
      - name: Clean Old Diagnostics Logs
        run: rm -f /home/runner/runners/2.311.0/_diag/*.log

      - name: Checkout Repository with Shallow Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Clean Up Before Zip
        run: |
          # Clean up unnecessary files and directories
          git clean -fdX

          # Optionally, remove files that should not be included in the deployment
          # rm -rf path/to/unwanted/file

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'wwwpaybitcoininth'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1BD8EEF748C44E4BBA516415DD1533A7 }}
